name: CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: yarn install
      run: |
        yarn install
      
    - name: yarn build
      run: |
        yarn run build

    - name: go to build dir
      run: |
        cd build

    - name: setup git glitch repo
      run: |
        git remote add destination ${{ secrets.glitch_git_URL }}
    
    - name: deploy to glitch
      run: |
        git push destination HEAD:master -f
