name: CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: yarn install
      run: |
        yarn install
      
    - name: yarn build
      run: |
        yarn run build;

    - name: setup glitch git
      run: |
        ls -lrt;
        git config --global --unset core.excludesfile;
        cd build;
        git init;
        git add *
        git remote add glitch ${{ secrets.glitch_git_URL }}

    - name: deploy to glitch
      run: |
        ls -lrt;
        git push glitch HEAD:master -f

